
-- insert into info_province;
insert into info_province(name) values("山西省");
insert into info_province(name) values("北京市");
insert into info_province(name) values("天津市");
insert into info_province(name) values("河北省");
insert into info_province(name) values("内蒙古自治区");
insert into info_province(name) values("辽宁省");
insert into info_province(name) values("吉林省");
insert into info_province(name) values("黑龙江省");
insert into info_province(name) values("上海市");
insert into info_province(name) values("江苏省");
insert into info_province(name) values("浙江省");
insert into info_province(name) values("安徽省");
insert into info_province(name) values("福建");
insert into info_province(name) values("江西省");
insert into info_province(name) values("山东省");
insert into info_province(name) values("河南省");
insert into info_province(name) values("湖北省");
insert into info_province(name) values("湖南省");
insert into info_province(name) values("广东省");
insert into info_province(name) values("广西壮族自治区");
insert into info_province(name) values("海南省");
insert into info_province(name) values("四川省");
insert into info_province(name) values("贵州省");
insert into info_province(name) values("云南省");
insert into info_province(name) values("重庆市");
insert into info_province(name) values("西藏自治区");
insert into info_province(name) values("陕西省");
insert into info_province(name) values("甘肃省");
insert into info_province(name) values("青海省");
insert into info_province(name) values("宁夏回族自治区");
insert into info_province(name) values("新疆维吾尔自治区");
insert into info_province(name) values("香港特别行政区");
insert into info_province(name) values("澳门特别行政区");
insert into info_province(name) values("台湾省");



-- insert into info_city;
insert into info_city(name) values("太原");
insert into info_city(name) values("大同");
insert into info_city(name) values("阳泉");
insert into info_city(name) values("长治");
insert into info_city(name) values("晋城");
insert into info_city(name) values("朔州");
insert into info_city(name) values("忻州");
insert into info_city(name) values("吕梁");
insert into info_city(name) values("晋中");
insert into info_city(name) values("临汾");
insert into info_city(name) values("运城");

-- insert into info_county;
insert into info_county(name, city_id) values("清徐", 1), ("阳曲", 1), ("娄烦", 1), ("古交", 1), ("迎泽区", 1), ("杏花岭区", 1), ("万柏林区", 1), ("尖草坪区", 1), ("小店区", 1);
insert into info_county(name, city_id) values("阳高", 2), ("天镇", 2), ("广灵", 2), ("灵丘", 2), ("浑源", 2), ("左云", 2);
insert into info_county(name, city_id) values("平定", 3), ("盂县", 3);
insert into info_county(name, city_id) values("襄垣", 4), ("屯留", 4), ("平顺", 4), ("黎城", 4), ("壶关", 4), ("长子", 4), ("武乡", 4), ("沁县", 4), ("沁源", 4), ("潞城", 4);
insert into info_county(name, city_id) values("沁水", 5), ("阳城", 5), ("陵川", 5), ("泽州", 5), ("高平", 5);
insert into info_county(name, city_id) values("山阴", 6), ("应县", 6), ("右玉", 6), ("怀仁", 6);
insert into info_county(name, city_id) values("原平", 7), ("定襄", 7), ("五台", 7), ("代县", 7), ("繁峙", 7), ("宁武", 7), ("静乐", 7), ("神池", 7), ("五寨", 7), ("岢岚", 7), ("河曲", 7), ("保德", 7), ("偏关", 7);
insert into info_county(name, city_id) values("孝义", 8), ("离石", 8), ("汾阳", 8), ("文水", 8), ("交城", 8), ("兴县", 8), ("临县", 8), ("柳林", 8), ("石楼", 8), ("岚县", 8), ("方山", 8), ("中阳", 8), ("交口", 8);
insert into info_county(name, city_id) values("介休", 9), ("榆社", 9), ("左权", 9), ("和顺", 9), ("昔阳", 9), ("寿阳", 9), ("太谷", 9), ("祁县", 9), ("平遥", 9), ("灵石", 9);
insert into info_county(name, city_id) values("侯马", 10), ("霍州", 10), ("曲沃", 10), ("翼城", 10), ("襄汾", 10), ("洪洞", 10), ("古县", 10), ("安泽", 10), ("浮山", 10), ("吉县", 10), ("乡宁", 10), ("蒲县", 10), ("大宁", 10), ("永和", 10), ("隰县", 10), ("汾西", 10);
insert into info_county(name, city_id) values("永济", 11), ("芮城", 11), ("临猗", 11), ("万荣", 11), ("新绛", 11), ("稷山", 11), ("闻喜", 11), ("夏肥", 11), ("绛县", 11), ("平陆", 11), ("垣曲", 11), ("河津", 11);


-- insert into info_department;
insert into info_department(name) values('文学院');
insert into info_department(name) values('外国语学院');
insert into info_department(name) values('政治与历史学院');
insert into info_department(name) values('教育科学与技术学院');
insert into info_department(name) values('数理学院');
insert into info_department(name) values('生物科学与技术学院');
insert into info_department(name) values('化学化工学院');
insert into info_department(name) values('信息技术与工程学院');
insert into info_department(name) values('音乐学院');
insert into info_department(name) values('体育学院');
insert into info_department(name) values('美术学院');
insert into info_department(name) values('机械学院');
insert into info_department(name) values('经济管理学院');
insert into info_department(name) values('旅游与公共管理学院');
insert into info_department(name) values('远程教育学院');
insert into info_department(name) values('继续教育学院');

-- insert into info_minority;
insert into info_minority(name) values('汉族');
insert into info_minority(name) values('壮族');
insert into info_minority(name) values('满族');
insert into info_minority(name) values('回族');
insert into info_minority(name) values('苗族');
insert into info_minority(name) values('维吾尔族');
insert into info_minority(name) values('土家族');
insert into info_minority(name) values('彝族');
insert into info_minority(name) values('蒙古族');
insert into info_minority(name) values('藏族');
insert into info_minority(name) values('布依族');
insert into info_minority(name) values('侗族');
insert into info_minority(name) values('瑶族');
insert into info_minority(name) values('朝鲜族');
insert into info_minority(name) values('白族');
insert into info_minority(name) values('哈尼族');
insert into info_minority(name) values('哈萨克族');
insert into info_minority(name) values('黎族');
insert into info_minority(name) values('傣族');
insert into info_minority(name) values('畲族');
insert into info_minority(name) values('傈僳族');
insert into info_minority(name) values('仡佬族');
insert into info_minority(name) values('东乡族');
insert into info_minority(name) values('高山族');
insert into info_minority(name) values('拉祜族');
insert into info_minority(name) values('水族');
insert into info_minority(name) values('佤族');
insert into info_minority(name) values('纳西族');
insert into info_minority(name) values('羌族');
insert into info_minority(name) values('土族');
insert into info_minority(name) values('仫佬族');
insert into info_minority(name) values('锡伯族');
insert into info_minority(name) values('柯尔克孜族');
insert into info_minority(name) values('达斡尔族');
insert into info_minority(name) values('景颇族');
insert into info_minority(name) values('毛南族');
insert into info_minority(name) values('撒拉族');
insert into info_minority(name) values('布朗族');
insert into info_minority(name) values('塔吉克族');
insert into info_minority(name) values('阿昌族');
insert into info_minority(name) values('普米族');
insert into info_minority(name) values('鄂温克族');
insert into info_minority(name) values('怒族');
insert into info_minority(name) values('京族');
insert into info_minority(name) values('基诺族');
insert into info_minority(name) values('德昂族');
insert into info_minority(name) values('保安族');
insert into info_minority(name) values('俄罗斯族');
insert into info_minority(name) values('裕固族');
insert into info_minority(name) values('乌孜别克族');
insert into info_minority(name) values('门巴族');
insert into info_minority(name) values('鄂伦春族');
insert into info_minority(name) values('独龙族');
insert into info_minority(name) values('塔塔尔族');
insert into info_minority(name) values('赫哲族');
insert into info_minority(name) values('珞巴族');

-- insert into info_section
insert into info_section(name) values("编辑中心");
insert into info_section(name) values("新闻中心");
insert into info_section(name) values("网视中心");
insert into info_section(name) values("管理中心");
insert into info_section(name) values("办公室");
