# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='市')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='县')),
                ('city', models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.City')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='院系名')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Minority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='民族名')),
            ],
        ),
        migrations.CreateModel(
            name='NativePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.City')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.County')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='省')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30, verbose_name='姓名')),
                ('student_id', models.CharField(default=' ', max_length=20, unique=True, verbose_name='学号')),
                ('mobile', models.CharField(default=' ', max_length=11, verbose_name='手机号')),
                ('qq', models.CharField(blank=True, default='', max_length=20, verbose_name='QQ')),
                ('majors', models.CharField(default=' ', max_length=100, verbose_name='专业')),
                ('dialect', models.CharField(default='', max_length=100, verbose_name='是否会方言')),
                ('leave', models.CharField(default='', max_length=100, verbose_name='是否需请假')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.City')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.County')),
                ('department', models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Department', verbose_name='院系')),
                ('minority', models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Minority', verbose_name='民族')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Province')),
                ('section', models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Section', verbose_name='部门')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.AddField(
            model_name='nativeplace',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Province'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Province'),
        ),
    ]
