# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.City'),
        ),
        migrations.AlterField(
            model_name='student',
            name='county',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.County'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Department', verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minority',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Minority', verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Province'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Info.Section', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=' ', max_length=20, verbose_name='学号'),
        ),
    ]
